### ISSUE TITLE
Illegal access warning

### ISSUE THREAD

**Issue by dtitov** [uio-bmi/crypt4gh#1]
Depending on the JVM, some users may see a warning during encryption:

```
Encryption initialized...
Done: <path>
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.commons.crypto.stream.CryptoInputStream (<path>/crypt4gh.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.apache.commons.crypto.stream.CryptoInputStream
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Assumption: it happens only on Java 9+ JVM.

**Comment by dtitov** [comment]
The issue is internal to Apache Crypto library and is reported to that project: https://issues.apache.org/jira/projects/CRYPTO/issues/CRYPTO-144

**Comment by ujar** [comment]
> The issue is internal to Apache Crypto library and is reported to that project: https://issues.apache.org/jira/projects/CRYPTO/issues/CRYPTO-144

Any guess when we can  get the issue resolved?

**Comment by dtitov** [comment]
@ujar, no idea, to be honest. You can follow the issue in their JIRA to be updated. As for now, it's not even assigned to anyone. Maybe because I created it with "Low" priority, because, in fact, it's just a warning.

**Comment by dtitov** [comment]
I'm closing this issue since Apache Crypto is not being used anymore in the new version of Crypt4GH.
